# 文件名：.github/workflows/build.yml
name: Build

on: 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello"
      - run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap qemu-user-static
          ./compile.sh BOARD=uefi-x86 BRANCH=current RELEASE=noble KERNEL_CONFIGURE=no PROGRESS_DISPLAY=plain
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: output/images/*.img*
